---
title: "eds_212_day2"
author: "Shale"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

## R Markdown EOD practice with calculus and penguins


### Calc practice A

```{r}
fx = expression(x^2)
df_dx = D(expr = fx, name = "x")
x = 3
eval(expr = df_dx)
```


### Calc practice B

```{r}
pa = expression(2*(3*a+2)^4 - 5)
dp_da = D(expr = pa, name = "a")
a = 1.2
eval(expr = dp_da)
```


### Calc practice C

```{r}
gt = expression((-4*t) / (t^2 + 1)^3)
dg_dt = D(expr = gt, name = "t")
t = 0
eval(expr = dg_dt)
```


### Calc practice higher order 

```{r}
gz = expression(4.6 - 1.9 * z^3)
dg_dz = D(expr = gz, name = "z")
dg_dz
d2z_dz2 = D(expr = dg_dz, name = "z")
d2z_dz2
```

### Calc practice partial derivatives

```{r}
fxyz = expression(2*(x^2)*y - 3*x + 1 + 4*(z^4)*x)
fx_part = D(expr = fxyz, name = "x")
fx_part
fy_part = D(expr = fxyz, name = "y")
fy_part
fz_part = D(expr = fxyz, name = "z")
fz_part
```

### ggplot2 practice

```{r}
fx = function(x) {
  (2.4 * exp(-0.05*x) * sin(x))
}
ggplot(data.frame(x = c(-0.5, 0.5)), aes(x=x)) +
         stat_function(fun = fx)
```

## And now, for something completely different: penguins :)

```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  labs(x = "Bill length (mm)", y = "Bill depth (mm)", title = "Ratio of Penguin bill length to depth by species")
```

## jitterplot

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(position = "jitter", aes(color = species)) +
  labs(x = "Species", y = "Flipper length (mm)", title = "Penguin Flipper Length by Species")
```

## For comparison,  to see the difference without jitter
```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_point(aes(color = species)) +
  labs(x = "Species", y = "Flipper length (mm)", title = "Penguin Flipper Length by Species")
```

